theme = "period"

baseURL = "https://santiagopastor.xyz"
paginate = 20
title = "Knowlege Archive"

markup.highlight.noClasses=false

[[menu.main]]
name = "Home"
url = "/"
weight = 1
#[[menu.main]]
#name = "Posts"
#url = "/_index.md"
#weight = 2
[[menu.main]]
name = "About me"
url = "/about/about"
weight = 3

[params]
logo = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAl2chF0OuqvNKaMXWlh9GPn5vlHpSl0pXgQ&usqp=CAU"
subTitle = "Un repositorio de mis apuntes"


[params.comment]
repo = "{org}/{repo}"
show = true
theme = "github-dark"

[params.widget.about]
description = "Sysadmin"
logo = "https://cdnb.artstation.com/p/assets/images/images/032/778/277/large/constantine-admech002.jpg?1607445059"
show = true
title = "Santiago Pastor Serrano"

[[params.widget.links.items]]
title = "Hugo"
url = "https://gohugo.io"

[[params.widget.links.items]]
title = "Theme period"
url = "https://github.com/idoubi/hugo-theme-period"

[params.widget.tags]
show = true
title = "Tags"
